# Generated by Django 4.1 on 2023-01-08 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategorieName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(null=b'I01\n', upload_to='media')),
                ('date', models.DateField(auto_now=True)),
                ('Owner', models.ForeignKey(blank=b'I01\n', null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.category')),
                ('watchlist', models.ManyToManyField(blank=b'I01\n', null=b'I01\n', related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
