# Generated by Django 4.1 on 2023-01-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_auction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='Owner',
            new_name='owner',
        ),
    ]
