# Generated by Django 4.1 on 2023-01-08 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='watchlist',
        ),
    ]
