# Generated by Django 4.1 on 2023-01-08 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_auction_owner_remove_auction_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='image',
        ),
        migrations.AddField(
            model_name='auction',
            name='owner',
            field=models.ForeignKey(blank=b'I01\n', null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='auction',
            name='watchlist',
            field=models.ManyToManyField(blank=b'I01\n', null=b'I01\n', related_name='watchlist', to=settings.AUTH_USER_MODEL),
            preserve_default=b'I01\n',
        ),
    ]
