# Generated by Django 4.1 on 2023-01-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_auction_date_remove_auction_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='date',
            field=models.DateField(auto_now=True, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
