# Generated by Django 4.1 on 2023-01-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(null=b'I01\n', upload_to='media'),
            preserve_default=b'I01\n',
        ),
    ]
