# Generated by Django 4.1 on 2023-01-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_bid_alter_auction_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
