# Generated by Django 4.1 on 2023-01-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
